In [ ]:
import geopandas as gpd
from pathlib import Path

In [21]:
FOLDER = "../data/raw/geospatial/transmountain"

line_gdf = gpd.read_file(
    Path(FOLDER, "transmountain_existing_raw.geojson")
)

facility_gdf = gpd.read_file(
    Path(FOLDER, "transmountain_facilities_raw.geojson")
)

In [22]:
line_gdf.columns

Index(['OBJECTID_1', 'geometry'], dtype='str')

In [44]:
line_gdf['pipeline_id'] = 'trans_mountain'
line_gdf['pipeline_name'] = 'Trans Mountain Pipeline'
line_gdf['geometry_role'] = 'corridor'
line_gdf['geometry_method'] = 'source_vector'
line_gdf['source_name'] = 'NRCan'

"Either:"
"-Authoritave = Official from a government site"
"-Derived = Used some sort of method to derive it"
"-Approximate = reconstructed or digitized"
line_gdf['accuracy_class'] = 'authoritative'

line_gdf['source_crs'] = line_gdf.crs.to_string() if line_gdf.crs else None
line_gdf.rename({"OBJECTID_1":"source_object_id"}, axis=1, inplace=True)

# We will validate the the only contain one so there should not be a break here
line_gdf['geometry_type'] = line_gdf.geom_type.unique().tolist()[0]

In [45]:
line_gdf = line_gdf[
    [
        "pipeline_id",
        "pipeline_name",
        "source_name",
        "source_object_id",
        "source_crs",
        "geometry_role",
        "geometry_method",
        "accuracy_class",
        "geometry",
    ]
]

In [46]:
line_gdf.head()

,pipeline_id,pipeline_name,source_name,source_object_id,source_crs,geometry_role,geometry_method,accuracy_class,geometry
0,trans_mountain,Trans Mountain Pipeline,NRCan,1,EPSG:4326,corridor,source_vector,authoritative,"MULTIPOLYGON (((-122.93282 49.26926, -122.9329..."

In [20]:
facility_gdf.iloc[:,:6].head(5)

,OBJECTID,PUMP_NAME,TYPE_,SYSTEM,ELEVATION,MUNICIPALI
0,1,Border Traps,Trap Site,Trans Mountain Puget Sound Pipeline,8,Abbotsford
1,2,Hinton,Station,Trans Mountain Pipeline (TMPL),1110,Yellowhead County
2,3,Jasper,Station,Trans Mountain Pipeline (TMPL),1049,Jasper
3,4,Westridge Marine Terminal,Terminal,Trans Mountain Pipeline (TMPL),0,Burnaby
4,5,Darfield,Station,Trans Mountain Pipeline (TMPL),391,Thompson-Nicola O

Two ouputs
    pipeline_geometry.parquet
    pipeline_facilities.parquet

Retain all the original data points, but normalize the column names. Also add what key they belong to - enbridge, tm, keystone etc.